### ISSUE TITLE
Missing package-lock.json file?

### ISSUE THREAD

**Issue by 4thAce** [BoundfoxStudios/action-hugo-link-check#1]
I tried the action but it is saying that isn't seeing the package-lock.json file created by npm ci
https://gist.github.com/4thAce/46174633a22f82f617b910f3bdd7a49c
I thought it could be because I specified @v1 but it does the same thing with @v2 or @v.2.0.1 as well.

**Comment by ManuelRauber** [comment]
> I tried the action but it is saying that isn't seeing the package-lock.json file created by npm ci https://gist.github.com/4thAce/46174633a22f82f617b910f3bdd7a49c I thought it could be because I specified @v1 but it does the same thing with @v2 or @v.2.0.1 as well.

Hi @4thAce 

Sorry, that's a missing documentation in this repo, because it uses npm to download the correct hugo binary.

Please take a look at this package.json file: https://github.com/BoundfoxStudios/community-project/blob/develop/docs/package.json#L15

You need `hugo-bin` as [a dependency](https://www.npmjs.com/package/hugo-bin) in the version you're running hugo.

That was the easiest setup to guarantee the correct hugo version for anyone that will clone the repo etc.

**Comment by 4thAce** [comment]
Thanks, I am past this issue now. I'll still need to figure out why I see some false positives marked as broken, but the application is quite usable.

**Comment by ManuelRauber** [comment]
> Thanks, I am past this issue now. I'll still need to figure out why I see some false positives marked as broken, but the application is quite usable.

Perfect!

Maybe one thing, because I ran into the same issue: Rate limiting. 

In my case, I'm using a Docsy generated site that contains a lot links to GitHub and at some point I hit githubs rate limit. So I removed some checks to specific auto-generated links (see here: https://github.com/BoundfoxStudios/fairy-tale-defender/blob/develop/.github/actions/hugo-check-broken-links/action.yml#L9).

Maybe that's somewhat useful for you.
